const USERS={student:{password:'student123',role:'student',name:'Raqiya Ibrahim'},teacher:{password:'teacher123',role:'teacher',name:'Teacher Ahmed'}};
const NAV={student:[['home','⌂','Home'],['workbook','▤','Workbook'],['progress','◔','Progress'],['leaderboard','★','Leaderboard'],['profile','○','Profile']],teacher:[['teacher-home','⌂','Dashboard'],['students','◎','Students'],['weaknesses','△','Weaknesses'],['reports','▦','Reports'],['teacher-leaderboard','★','Leaderboard']]};
const SAMPLE_STUDENTS=[
 {name:'Hodan Ali',points:680,completion:91,vocabulary:88,grammar:81,listening:76,writing:84,weak:'Listening for detail'},
 {name:'Mohamed Nur',points:645,completion:86,vocabulary:84,grammar:74,listening:71,writing:78,weak:'Present simple accuracy'},
 {name:'Raqiya Ibrahim',points:610,completion:78,vocabulary:72,grammar:65,listening:61,writing:68,weak:'Listening for key details'},
 {name:'Sahra Omar',points:585,completion:72,vocabulary:69,grammar:63,listening:66,writing:62,weak:'Sentence organisation'},
 {name:'Abdi Hassan',points:540,completion:68,vocabulary:75,grammar:58,listening:55,writing:60,weak:'Grammar in complete sentences'}
];
const LESSON={
 id:'w1l1',title:'Your starting point',outcome:'Identify your current English strengths and one clear fluency goal.',
 expressions:[
  {text:'Let me think for a moment.',job:'buy time without becoming silent'},
  {text:'What I mean is…',job:'say an idea again more clearly'},
  {text:'Could you repeat the question?',job:'ask to hear a question again'},
  {text:'In my experience…',job:'connect an answer to real life'},
  {text:'One goal I have is…',job:'state a learning or career goal'}
 ],
 listening:`Teacher: When do you normally use English? Student: In my experience, I use English at work and when I watch training videos. Teacher: What would you like to improve most? Student: Let me think for a moment. One goal I have is to answer people without long pauses. Teacher: What already feels comfortable? Student: Reading is easier for me, but I want my speaking to feel more natural.`
};
let session=null,currentPage='home',currentStep='vocabulary';
const storeKey='fluencyFirstMvp';
function getStore(){return JSON.parse(localStorage.getItem(storeKey)||'{"scores":{},"writing":"","points":610,"completed":[]}')}
function setStore(data){localStorage.setItem(storeKey,JSON.stringify(data))}
function $(id){return document.getElementById(id)}

document.addEventListener('DOMContentLoaded',()=>{
 $('loginForm').addEventListener('submit',e=>{e.preventDefault();login($('username').value.trim(),$('password').value)});
 document.querySelectorAll('.demo-login').forEach(b=>b.addEventListener('click',()=>{const u=b.dataset.user;login(u,USERS[u].password)}));
 $('logoutBtn').addEventListener('click',logout);
});
function login(username,password){const u=USERS[username];if(!u||u.password!==password){$('loginError').textContent='Username or password is incorrect.';return}$('loginError').textContent='';session={username,...u};$('loginScreen').classList.add('hidden');$('app').classList.remove('hidden');$('sidebarName').textContent=u.name;$('sidebarRole').textContent=u.role==='teacher'?'Teacher':'Student';$('sidebarAvatar').textContent=u.name[0];currentPage=u.role==='teacher'?'teacher-home':'home';renderNav();renderPage()}
function logout(){session=null;$('app').classList.add('hidden');$('loginScreen').classList.remove('hidden');$('password').value=''}
function renderNav(){const items=NAV[session.role];const html=items.map(([id,icon,label])=>`<button class="nav-btn ${currentPage===id?'active':''}" data-page="${id}"><span class="nav-icon">${icon}</span>${label}</button>`).join('');$('sideNav').innerHTML=html;$('bottomNav').innerHTML=html;document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{currentPage=b.dataset.page;renderNav();renderPage();window.scrollTo(0,0)})}
function title(eyebrow,heading){$('pageEyebrow').textContent=eyebrow;$('pageTitle').textContent=heading}
function progress(value){return `<div class="progress"><span style="width:${value}%"></span></div>`}
function renderPage(){if(session.role==='student')renderStudent();else renderTeacher()}
function renderStudent(){switch(currentPage){case'home':studentHome();break;case'workbook':workbook();break;case'progress':studentProgress();break;case'leaderboard':leaderboard(false);break;case'profile':profile();break;default:studentHome()}}
function studentHome(){title('Student dashboard','Home');const s=getStore();$('content').innerHTML=`
 <section class="hero"><div><p class="eyebrow">Week 1 · Fluency Foundations</p><h1>Good evening, Raqiya</h1><p>Your live class is for speaking. Use this workbook to strengthen the language you need before class.</p></div><div class="hero-action"><small>Continue learning</small><strong>Lesson 1 · ${LESSON.title}</strong><button class="secondary-btn" id="continueBtn">Continue workbook →</button></div></section>
 <section class="section"><div class="section-head"><div><h3>Your skills</h3><p>Current mastery estimate from your practice.</p></div><span class="pill teal">Overall ${overallScore()}%</span></div><div class="grid grid-4">${skillCard('Vocabulary',skillScore('vocabulary'),'Words & expressions')}${skillCard('Grammar',skillScore('grammar'),'Sentence accuracy')}${skillCard('Listening',skillScore('listening'),'Meaning & detail')}${skillCard('Writing',skillScore('writing'),'Clear written ideas')}</div></section>
 <section class="section grid grid-2"><div class="card"><div class="section-head"><div><h3>Your focus this week</h3><p>Based on your weakest practice area.</p></div></div><div class="weakness"><strong>${weakestSkill().label}</strong><span>${weakestSkill().tip}</span></div><button class="secondary-btn" id="practiceWeakBtn">Practise this skill</button></div><div class="card"><div class="section-head"><div><h3>Class position</h3><p>Points reward practice, improvement and consistency.</p></div></div><div style="display:flex;align-items:end;justify-content:space-between"><div><strong style="font-size:2.2rem">#3</strong><div class="muted">of 5 students</div></div><div style="text-align:right"><strong>${s.points||610} pts</strong><div class="muted">70 pts to #1</div></div></div></div></section>`;
 $('continueBtn').onclick=()=>{currentPage='workbook';renderNav();workbook()};$('practiceWeakBtn').onclick=()=>{currentPage='workbook';currentStep=weakestSkill().key;renderNav();workbook()}}
function skillCard(name,value,desc){return `<div class="card metric-card"><div class="metric-top"><span class="pill">${desc}</span><strong>${value}%</strong></div><h4 style="margin:0">${name}</h4>${progress(value)}</div>`}
function skillScore(key){const base={vocabulary:72,grammar:65,listening:61,writing:68};const s=getStore().scores||{};return s[key]??base[key]}
function overallScore(){return Math.round(['vocabulary','grammar','listening','writing'].reduce((a,k)=>a+skillScore(k),0)/4)}
function weakestSkill(){const scores=['vocabulary','grammar','listening','writing'].map(k=>[k,skillScore(k)]).sort((a,b)=>a[1]-b[1]);const k=scores[0][0],tips={vocabulary:'Retrieve useful expressions without looking at the language bank.',grammar:'Build complete, accurate simple sentences before you speak.',listening:'Listen for the main idea first, then key details on the second play.',writing:'Organise a short answer with a clear point, reason and example.'};return{key:k,label:k[0].toUpperCase()+k.slice(1),tip:tips[k]}}
function workbook(){title('Digital workbook','Week 1 · Lesson 1');const steps=[['vocabulary','1','Vocabulary'],['listening','2','Listening'],['grammar','3','Grammar'],['writing','4','Writing'],['review','5','Review']];$('content').innerHTML=`<section class="section" style="margin-top:0"><div class="section-head"><div><span class="pill teal">A2+ → B1</span><h3 style="margin-top:8px">${LESSON.title}</h3><p>${LESSON.outcome}</p></div><div><strong>${lessonProgress()}% complete</strong></div></div><div class="activity-layout"><div class="activity-steps">${steps.map(([id,n,l])=>`<button class="step-btn ${currentStep===id?'active':''}" data-step="${id}"><span>${n}. ${l}</span><span>${stepDone(id)?'✓':''}</span></button>`).join('')}</div><div id="activityPanel" class="activity-card"></div></div></section>`;document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{currentStep=b.dataset.step;workbook()});renderActivity()}
function stepDone(step){return getStore().completed?.includes(step)}
function markDone(step,score){const s=getStore();s.completed=s.completed||[];if(!s.completed.includes(step))s.completed.push(step);s.scores=s.scores||{};if(score!=null)s.scores[step]=score;s.points=(s.points||610)+10;setStore(s)}
function lessonProgress(){return Math.round((getStore().completed?.length||0)/5*100)}
function renderActivity(){const p=$('activityPanel');if(currentStep==='vocabulary')p.innerHTML=vocabActivity();if(currentStep==='listening')p.innerHTML=listeningActivity();if(currentStep==='grammar')p.innerHTML=grammarActivity();if(currentStep==='writing')p.innerHTML=writingActivity();if(currentStep==='review')p.innerHTML=reviewActivity();wireActivity()}
function vocabActivity(){const qs=[['You need a few seconds to organise your answer.','Let me think for a moment.'],['You want to connect your answer to something that happened to you.','In my experience…'],['You did not hear the teacher clearly.','Could you repeat the question?'],['You want to explain your learning target.','One goal I have is…']];const opts=LESSON.expressions.map(x=>x.text);return `<p class="eyebrow">Step 1 · Vocabulary</p><h3>Useful expressions for keeping a conversation moving</h3><p class="muted">Start with recognition. Choose the expression that best does each communication job.</p>${qs.map((q,i)=>`<div class="question"><p>${i+1}. ${q[0]}</p><select data-vocab="${i}" data-answer="${escapeAttr(q[1])}"><option value="">Choose an expression</option>${opts.map(o=>`<option>${o}</option>`).join('')}</select></div>`).join('')}<div id="activityFeedback"></div><button class="primary-btn" id="checkActivity">Check answers</button>`}
function listeningActivity(){return `<p class="eyebrow">Step 2 · Listening</p><h3>Listen for meaning, then detail</h3><p class="muted">Play the audio once for the main idea. Play it again before answering the detail questions.</p><div class="audio-box"><button id="playAudio" class="play-btn">▶</button><div><strong>Conversation: English goals</strong><div class="muted">About 35 seconds · play up to 3 times</div></div></div><div class="question"><p>1. What is the student's main goal?</p>${radio('l1',['Read faster','Speak with fewer long pauses','Write longer reports'],'Speak with fewer long pauses')}</div><div class="question"><p>2. Where does the student already use English?</p>${radio('l2',['At work and with training videos','Only at school','Only when travelling'],'At work and with training videos')}</div><div class="question"><p>3. Which skill already feels easier?</p>${radio('l3',['Speaking','Reading','Pronunciation'],'Reading')}</div><div id="activityFeedback"></div><button class="primary-btn" id="checkActivity">Check listening</button>`}
function grammarActivity(){const items=[['Which is a complete, accurate sentence?',['I use English at work.','I English at work.','Use English work.'],'I use English at work.'],['Choose the best sentence about a goal.',['One goal I have is speak more confident.','One goal I have is to speak more confidently.','One goal have speaking confidently.'],'One goal I have is to speak more confidently.'],['Choose the accurate question.',['Where you use English?','Where do you use English?','Where does you use English?'],'Where do you use English?']];return `<p class="eyebrow">Step 3 · Grammar</p><h3>Complete simple sentences</h3><p class="muted">The live lesson observes accuracy without turning into a long grammar lecture. Here you can practise the sentence patterns privately.</p>${items.map((q,i)=>`<div class="question"><p>${i+1}. ${q[0]}</p>${radio('g'+i,q[1],q[2])}</div>`).join('')}<div id="activityFeedback"></div><button class="primary-btn" id="checkActivity">Check grammar</button>`}
function writingActivity(){const s=getStore();return `<p class="eyebrow">Step 4 · Writing</p><h3>Turn your speaking goal into a short written plan</h3><p class="muted">Write 40–80 words. Include: where you use English, one thing you already do well, one difficult speaking situation, and one clear 12-week goal.</p><div class="teacher-note"><strong>Helpful starters:</strong> In my experience… · I feel confident when… · A difficult situation for me is… · One goal I have is…</div><div class="writing-box" style="margin-top:16px"><textarea id="writingText" placeholder="Write your short plan here…">${escapeHtml(s.writing||'')}</textarea><div id="wordCount" class="word-count">0 words</div></div><div id="activityFeedback"></div><button class="primary-btn" id="saveWriting">Save writing</button>`}
function reviewActivity(){const weak=weakestSkill();return `<p class="eyebrow">Step 5 · Review</p><h3>Ready for your live class</h3><p class="muted">The workbook uses your results to decide what deserves another short review.</p><div class="grid grid-2"><div class="card"><span class="pill teal">Current focus</span><h3>${weak.label}</h3><p>${weak.tip}</p>${progress(skillScore(weak.key))}</div><div class="card"><span class="pill gold">Speaking preparation</span><h3>2-minute baseline</h3><p>Prepare only three keywords: <strong>use · strength · goal</strong>. In class, speak from the keywords rather than a full script.</p></div></div><div class="recommendation section"><p class="eyebrow">Before the live lesson</p><h3>Complete the message, then improve it.</h3><p>Do not wait for perfect English. Your teacher can use your workbook results to choose the most useful correction.</p></div><button class="primary-btn section" id="finishReview">Mark lesson ready</button>`}
function radio(name,options,answer){return `<div class="choice-list">${options.map(o=>`<label class="choice"><input type="radio" name="${name}" value="${escapeAttr(o)}" data-answer="${escapeAttr(answer)}"> <span>${o}</span></label>`).join('')}</div>`}
function wireActivity(){if($('playAudio'))$('playAudio').onclick=()=>speak(LESSON.listening);if($('checkActivity'))$('checkActivity').onclick=checkCurrent;if($('writingText')){const t=$('writingText'),wc=$('wordCount');const count=()=>wc.textContent=`${t.value.trim()?t.value.trim().split(/\s+/).length:0} words`;t.oninput=count;count()}if($('saveWriting'))$('saveWriting').onclick=()=>{const t=$('writingText'),words=t.value.trim()?t.value.trim().split(/\s+/).length:0;const f=$('activityFeedback');if(words<40){f.innerHTML='<div class="feedback bad">Write at least 40 words so the teacher has enough evidence to review.</div>';return}const s=getStore();s.writing=t.value;s.scores=s.scores||{};s.scores.writing=Math.min(100,65+Math.round(Math.min(words,80)/8));setStore(s);markDone('writing',s.scores.writing);f.innerHTML='<div class="feedback good">Saved. Your teacher can review this writing sample.</div>';setTimeout(workbook,700)};if($('finishReview'))$('finishReview').onclick=()=>{markDone('review');workbook()}}
function checkCurrent(){let total=0,correct=0;if(currentStep==='vocabulary'){document.querySelectorAll('[data-vocab]').forEach(el=>{total++;if(el.value===el.dataset.answer)correct++})}else{const groups=[...new Set([...document.querySelectorAll('input[type=radio]')].map(x=>x.name))];total=groups.length;groups.forEach(g=>{const c=document.querySelector(`input[name="${g}"]:checked`);if(c&&c.value===c.dataset.answer)correct++})}const score=Math.round(correct/total*100);const f=$('activityFeedback');f.innerHTML=`<div class="feedback ${score>=70?'good':'bad'}">${correct}/${total} correct · ${score}%. ${score>=70?'Good work. Move on when ready.':'Review the examples and try again.'}</div>`;if(score>=70){markDone(currentStep,score);setTimeout(workbook,850)}}
function speak(text){if(!('speechSynthesis'in window))return alert('Audio playback is not supported in this browser.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.88;u.lang='en-US';speechSynthesis.speak(u)}
function studentProgress(){title('Learning analytics','My progress');const base=[['Vocabulary',skillScore('vocabulary')],['Grammar',skillScore('grammar')],['Listening',skillScore('listening')],['Writing',skillScore('writing')]];$('content').innerHTML=`<section class="grid grid-4">${base.map(x=>skillCard(x[0],x[1],x[1]>=75?'On track':'Keep practising')).join('')}</section><section class="section grid grid-2"><div class="card"><h3>Baseline → now</h3><p class="muted">Your course uses repeated evidence, not one test score.</p><div style="display:grid;gap:16px;margin-top:20px">${[['Conversation',55,68],['Speaking without long pauses',48,62],['Grammar while speaking',52,65]].map(r=>`<div><div style="display:flex;justify-content:space-between"><strong>${r[0]}</strong><span>${r[1]}% → ${r[2]}%</span></div>${progress(r[2])}</div>`).join('')}</div></div><div class="card"><h3>What to review next</h3><div class="weakness"><strong>${weakestSkill().label}</strong><span>${weakestSkill().tip}</span></div><p class="teacher-note">Your private weakness data is not shown on the class leaderboard.</p></div></section>`}
function leaderboard(teacher){title('Motivation','Class leaderboard');const data=[...SAMPLE_STUDENTS].sort((a,b)=>b.points-a.points);$('content').innerHTML=`<div class="card"><div class="section-head"><div><h3>Fluency Foundations · Week 1</h3><p>Points reward completion, improvement and consistent review — not English level alone.</p></div><span class="pill gold">Weekly</span></div>${data.map((s,i)=>`<div class="leader-row ${s.name==='Raqiya Ibrahim'&&!teacher?'me':''}"><div class="rank">${i+1}</div><div class="student-cell"><div class="avatar">${s.name[0]}</div><div><strong>${s.name}${s.name==='Raqiya Ibrahim'&&!teacher?' · You':''}</strong><div class="muted">${s.completion}% workbook complete</div></div></div><strong>${s.points} pts</strong></div>`).join('')}</div>`}
function profile(){title('Account','Profile');$('content').innerHTML=`<div class="grid grid-2"><div class="card"><h3>Raqiya Ibrahim</h3><p class="muted">Fluency Foundations · A2+ → B1</p><div class="question"><p>Username</p><span>student</span></div><div class="question"><p>Teacher</p><span>Teacher Ahmed</span></div><button class="ghost-btn">Request password reset</button></div><div class="card"><h3>Learning targets</h3><p>Week 4: speak for two minutes with fewer long pauses.</p><p>Week 8: answer interview questions more clearly.</p><p>Week 12: manage a professional conversation independently.</p></div></div>`}
function renderTeacher(){switch(currentPage){case'teacher-home':teacherHome();break;case'students':students();break;case'weaknesses':weaknesses();break;case'reports':reports();break;case'teacher-leaderboard':leaderboard(true);break;default:teacherHome()}}
function teacherHome(){title('Teacher dashboard','Class overview');const active=SAMPLE_STUDENTS.filter(s=>s.completion>=70).length;$('content').innerHTML=`<section class="hero"><div><p class="eyebrow">Fluency Foundations</p><h1>Teach what the data says matters.</h1><p>Workbook practice happens outside class. Your dashboard turns mistakes into revision priorities for the next live speaking lesson.</p></div><div class="hero-action"><small>Next class recommendation</small><strong>Listening for key details</strong><button class="secondary-btn" id="openWeak">View weakness map →</button></div></section><section class="section grid grid-4">${metric('Students','5','Enrolled')}${metric('Active',''+active,'70%+ complete')}${metric('Completion','79%','Class average')}${metric('Need support','3','Priority students')}</section><section class="section grid grid-2"><div class="card"><div class="section-head"><div><h3>Needs your attention</h3><p>Lowest current mastery areas.</p></div></div>${SAMPLE_STUDENTS.slice(2).map(s=>`<div class="weakness"><strong>${s.name} · ${s.weak}</strong><span>Review before or during the next live lesson.</span></div>`).join('')}</div><div class="recommendation"><p class="eyebrow">Recommended revision</p><h3>10-minute Listening for Detail drill</h3><p>3 of 5 learners are below 65% in listening. Start the next class with one short listen → keyword note → retell cycle before the speaking mission.</p><button class="secondary-btn" id="openStudents">See students</button></div></section>`;$('openWeak').onclick=()=>{currentPage='weaknesses';renderNav();weaknesses()};$('openStudents').onclick=()=>{currentPage='students';renderNav();students()}}
function metric(label,value,sub){return `<div class="card metric-card"><span class="pill">${sub}</span><strong>${value}</strong><h4 style="margin:0">${label}</h4></div>`}
function students(){title('Class management','Students');$('content').innerHTML=`<div class="section-head"><div><h3>Fluency Foundations</h3><p>Teacher-managed student accounts and current mastery.</p></div><button class="primary-btn" id="addStudent">+ Add student</button></div><div class="card table-wrap"><table class="data-table"><thead><tr><th>Student</th><th>Completion</th><th>Vocabulary</th><th>Grammar</th><th>Listening</th><th>Writing</th><th>Primary weakness</th><th></th></tr></thead><tbody>${SAMPLE_STUDENTS.map(s=>`<tr><td><div class="student-cell"><div class="avatar">${s.name[0]}</div><strong>${s.name}</strong></div></td><td>${s.completion}%</td><td>${s.vocabulary}%</td><td>${s.grammar}%</td><td>${s.listening}%</td><td>${s.writing}%</td><td>${s.weak}</td><td><button class="ghost-btn" onclick="alert('Prototype: student detail view will connect to the production database.')">Review</button></td></tr>`).join('')}</tbody></table></div><p class="teacher-note section">Production account management will create usernames and temporary passwords securely. Teachers will reset passwords rather than view stored passwords.</p>`;$('addStudent').onclick=()=>alert('Prototype: secure student creation will be enabled when the backend is connected.')}
function weaknesses(){title('Teacher intelligence','Weakness map');const areas=[['Listening for key details',3,58],['Complete simple sentences',2,62],['Vocabulary retrieval',2,67],['Short writing organisation',1,71]];$('content').innerHTML=`<div class="grid grid-2"><div class="card"><h3>Class-wide weaknesses</h3><p class="muted">Prioritised by number of students affected and current mastery.</p>${areas.map(a=>`<div class="question"><div style="display:flex;justify-content:space-between"><strong>${a[0]}</strong><span class="pill ${a[2]<65?'gold':'teal'}">${a[1]} students</span></div><div style="margin-top:10px">${progress(a[2])}</div><small class="muted">Class mastery ${a[2]}%</small></div>`).join('')}</div><div><div class="recommendation"><p class="eyebrow">Best use of live time</p><h3>Review: Listening → keywords → retell</h3><p>Keep the explanation short. Let students listen once for meaning, once for details, take three keywords, then speak from those keywords.</p></div><div class="card section"><h3>Why this is flagged</h3><p>Raqiya: 61%</p><p>Abdi: 55%</p><p>Sahra: 66%</p><p class="muted">The teacher sees mastery. Students only see their own private focus area.</p></div></div></div>`}
function reports(){title('Evidence','Reports');$('content').innerHTML=`<div class="grid grid-3">${metric('Workbook completion','79%','Current week')}${metric('Average mastery','71%','4 tracked skills')}${metric('Evidence saved','9','Writing + practice')}</div><section class="section card"><div class="section-head"><div><h3>Course evidence checkpoints</h3><p>Designed to compare starting point, mid-course and end-of-course performance.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Checkpoint</th><th>Conversation</th><th>Pauses</th><th>Workplace</th><th>Interviews</th><th>Presentations</th><th>Grammar while speaking</th></tr></thead><tbody><tr><td>Start</td><td>55%</td><td>48%</td><td>56%</td><td>44%</td><td>42%</td><td>52%</td></tr><tr><td>Week 6</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>Week 12</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr></tbody></table></div></section>`}
function escapeAttr(s){return String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;')}
function escapeHtml(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
